name: dipdup_mcp_tutorial

services:
  db:
    image: postgres:16
    ports:
      - "${POSTGRES_HOST_PORT:-5432}:5432"
    volumes:
      - db:/var/lib/postgresql/data
    restart: always
    # env_file: .env
    environment:
      - POSTGRES_USER=dipdup
      - POSTGRES_DB=dipdup
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dipdup"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db:
